### PR TITLE
Rework status cron and send mails only on changes

### LINKED ISSUE #55: Kastenwesen status emails should not be send twice
Currently admins get spammed by `kastenwesen status` mails if there is an error. We should send only one email and if there is no change, we shouldn't send the same email again.

### PR DESCRIPTION
**Pull request by sedrubal**
Fixes #55
Mails will be send only if the message is different to the mail send
before. The overall status of each container matters.
The last status will be saved as json.

### CODE REVIEW

**Review by mgmax — CHANGES_REQUESTED** [review]
While this solves the spam problem, I suspect it may introduce "glitch" emails when containers are restarted. No mails should be sent while a kastenwesen instance is running (and that's why `status` always exits 0 in this case).

Currently, the script will also send mails if the status text changes even if the exit code was 0 before and after.
This will happen during kastenwesen operations, e.g. "everything okay -> something broken, instance active -> waiting for startup gracetime -> everything okay"

It will also send mails if a kastenwesen operation is started while something is broken, because then `status` temporarily returns `0` while the operation is running, which means the exit code changes from 1 to 0 and possibly back.

cron_status.py should have a license header.

(Also, the new variable name `time_sleep_before_test` doesn't make much sense grammatically, but I don't really care about that.)

**Comment by sedrubal** [comment]
Thanks for your review. I completely agree.

Question: `other_instance_running` always seems to be `False` because, `shell` is in `read_only_args`. Am I right? So we can remove this logic. I also think that test won't/shouldn't fail even if another instance of `kastenwesen` is running...

**Comment by sedrubal** [comment]
I implemented something like a flapping detection by investigating (currently) the last 5 states.

The only thing that currently doesn't work is sending mails when the status for one container was `OKAY`/`FAILED` and then 5 times `STARTING` and then `FAILED`/`OKAY`

**Comment by mgmax** [comment]
The flapping detection is a quite complicated problem. I don't know an easy solution. Maybe we should leave it out at first and see if we can live without it?

Nagios seems to count state changes in the last 21 runs and then apply a threshold with hysteresis, e.g., switch to flapping if there were more than 10 transitions and switch back if less than 5. For this, you also need to store the last overall status, i.e. flapping or not.

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html

I think you should increase `FLAPPING_HYSTERESIS` (which is not actually a hysteresis) to something like 20 and then only tag the state as flapping if it has at least one `GOOD -> FAILED -> GOOD -> FAILED` cycle.

**Comment by sedrubal** [comment]
Ok I can increase `FLAPPING_HYSTERESIS` to let's say `10`: No job will need more than 10 minutes to start up and it's ok if we get mailed with a delay of 10 minutes.

But I already spent 2 days for this and I can't spend more time, sorry.

Would you say, it's better than right now and we can merge this while opening a new issue to improve flapping handling?

(Why do you think this is not a hysteresis?)

**Pull request merged**
