### PR TITLE
Move status files to /var/lib/kastenwesen/

### PR DESCRIPTION
**Pull request by sedrubal**

### CODE REVIEW

**Comment by sedrubal** [comment]
@mgmax Does travis have root permissions? Or why is `mkdir /var/lib/kastenwesen/` failing?

**Comment by sedrubal** [comment]
Can we merge this?

**Review by mgmax — CHANGES_REQUESTED** [review]
The travis build is broken. Feel free to merge as soon as the build is fixed.

**Comment by mgmax** [comment]
It seems that travis isn't running as root. Before your change, kastenwesen could also be run by a normal user who is in the `docker` group, and that's why it worked with travis.

**Comment by sedrubal** [comment]
Ok now it is working 👼 I'll merge and deploy it.

**Comment by sedrubal** [comment]
Oops. This one is merged but I removed the branch before pushing the merge commit...

**Pull request closed without merging**
