### PR TITLE
Make kastenwesen python3 compatible

### PR DESCRIPTION
**Pull request by sedrubal**
Additionally I removed the `flush` logic, because I didn't find a reason for it...

### CODE REVIEW

**Comment by mgmax** [comment]
The flush logic is required whenever the output is not directly connected to a real terminal. Then python 2 (and 3?) uses buffered IO and progress messages may appear long after the action is finished.  see http://www.sudhirwarrier.com/python-unbuffered/

**Comment by mgmax** [comment]
By the way, does the code really work with python 3? Last time I checked there was no Docker library available.

**Comment by mgmax** [comment]
/usr/bin/python points to python2, at least that is what the python standard recommends AFAIR. We should rather throw away all backwards compatibility and call Python3 explicitly, because it is not fun to develop for two different languages at the same time.

**Comment by sedrubal** [comment]
> By the way, does the code really work with python 3? Last time I checked there was no Docker library available.

Yes, docker is available in python3:

```sh
$ pip2 show docker-py
---
Metadata-Version: 1.1
Name: docker-py
Version: 1.10.6
Summary: Python client for Docker.
Home-page: https://github.com/docker/docker-py/
[snip]
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
[snip]
$ pip3 show docker-py
Name: docker-py
Version: 1.10.6
Summary: Python client for Docker.
[snip]
```

> /usr/bin/python points to python2, at least that is what the python standard recommends AFAIR. 

Yes

> We should rather throw away all backwards compatibility and call Python3 explicitly, because it is not fun to develop for two different languages at the same time.

Yeay :smile:

**Comment by sedrubal** [comment]
Can we merge?

**Pull request merged**
