### PR TITLE
allow auto-upgrade to be disabled and forced

### PR DESCRIPTION
**Pull request by patkan**
This will allow to just call check-for-updates with --auto-upgrade and disable it by setting disable_auto_upgrade to True in kastenwesen_config.py.

### CODE REVIEW

**Comment by mgmax** [comment]
Shouldn't we somehow distinguish between the cronjob and a manual call of `--auto-upgrade` from the terminal?
Alternatively, the error message should be more constructive ("use --force-upgrade if you really want to") or ask for a "yes/no" answer from the standard input to temporarily ignore the config setting.

**Comment by patkan** [comment]
OK, how about this:
I remove force-upgrade.
If the auto-upgrade is enabled, then it is always executed. If it is disabled the. It asks whether it should really upgrade and with no standard input does not proceed.

**Comment by mgmax** [comment]
sounds good.

**Comment by patkan** [comment]
I think this should now be the described behavior. Please review and feel free to merge if the review is positive.

**Comment by mgmax** [comment]
The diff looks good. Please merge.

Maybe we should adjust the cronjob so that rebuilds only happen at night instead of three times per day?

**Comment by patkan** [comment]
Sounds like a good idea, I will do that when installing the new version.

**Pull request merged**
