### PR TITLE
Remove `-f` when `docker tag`

### PR DESCRIPTION
**Pull request by sedrubal**
My docker has no option `-f` :smile:

### CODE REVIEW

**Comment by mgmax** [comment]
This will break things for Docker < 1.10, especially on Ubuntu trusty. 

Force tagging (creating multiple tags if required) was enabled as default in 1.10 and -f was finally removed in 1.12.

**Comment by sedrubal** [comment]
Oh sorry that I didn't read the docs... So I'll close this for now...

**Comment by mgmax** [comment]
Hm, for newer docker versions it definitely is a problem, so some version-dependent fix would be useful.

**Comment by sedrubal** [comment]
Ok, you're right. So this should work.

**Review by mgmax — APPROVED** [review]
Tested with the ubuntu trusty VM. I improved the code comments, please have a look and feel free to rebase and merge.

**Pull request merged**
